"""
Language definitions for each STT engine.

WHISPER_LANGUAGES  – all languages supported by openai-whisper (source only).
                     When task="translate" the output is always English.
                     When task="transcribe" the output matches the source.

QWEN_LANGUAGES     – the 30 languages supported by Qwen3-ASR-0.6B (source only).
                     Qwen3-ASR is ASR-only: output is always in the source language.
"""

VALID_WHISPER_SIZES = ("tiny", "base", "small", "medium", "large")

# Codes follow ISO 639-1 (or ISO 639-3 where 639-1 doesn't exist)
# matching the string identifiers accepted by openai-whisper.
WHISPER_LANGUAGES: dict[str, str] = {
    "af":  "Afrikaans",
    "sq":  "Albanian",
    "am":  "Amharic",
    "ar":  "Arabic",
    "hy":  "Armenian",
    "as":  "Assamese",
    "az":  "Azerbaijani",
    "ba":  "Bashkir",
    "eu":  "Basque",
    "be":  "Belarusian",
    "bn":  "Bengali",
    "bs":  "Bosnian",
    "br":  "Breton",
    "bg":  "Bulgarian",
    "ca":  "Catalan",
    "zh":  "Chinese",
    "hr":  "Croatian",
    "cs":  "Czech",
    "da":  "Danish",
    "nl":  "Dutch",
    "en":  "English",
    "et":  "Estonian",
    "fo":  "Faroese",
    "fi":  "Finnish",
    "fr":  "French",
    "gl":  "Galician",
    "ka":  "Georgian",
    "de":  "German",
    "el":  "Greek",
    "gu":  "Gujarati",
    "ht":  "Haitian Creole",
    "ha":  "Hausa",
    "haw": "Hawaiian",
    "he":  "Hebrew",
    "hi":  "Hindi",
    "hu":  "Hungarian",
    "is":  "Icelandic",
    "id":  "Indonesian",
    "it":  "Italian",
    "ja":  "Japanese",
    "jw":  "Javanese",
    "kn":  "Kannada",
    "kk":  "Kazakh",
    "km":  "Khmer",
    "ko":  "Korean",
    "lo":  "Lao",
    "la":  "Latin",
    "lv":  "Latvian",
    "ln":  "Lingala",
    "lt":  "Lithuanian",
    "lb":  "Luxembourgish",
    "mk":  "Macedonian",
    "mg":  "Malagasy",
    "ms":  "Malay",
    "ml":  "Malayalam",
    "mt":  "Maltese",
    "mi":  "Maori",
    "mr":  "Marathi",
    "mn":  "Mongolian",
    "my":  "Myanmar",
    "ne":  "Nepali",
    "no":  "Norwegian",
    "nn":  "Nynorsk",
    "oc":  "Occitan",
    "ps":  "Pashto",
    "fa":  "Persian",
    "pl":  "Polish",
    "pt":  "Portuguese",
    "pa":  "Punjabi",
    "ro":  "Romanian",
    "ru":  "Russian",
    "sa":  "Sanskrit",
    "sr":  "Serbian",
    "sn":  "Shona",
    "sd":  "Sindhi",
    "si":  "Sinhala",
    "sk":  "Slovak",
    "sl":  "Slovenian",
    "so":  "Somali",
    "es":  "Spanish",
    "su":  "Sundanese",
    "sw":  "Swahili",
    "sv":  "Swedish",
    "tl":  "Tagalog",
    "tg":  "Tajik",
    "ta":  "Tamil",
    "tt":  "Tatar",
    "te":  "Telugu",
    "th":  "Thai",
    "bo":  "Tibetan",
    "tr":  "Turkish",
    "tk":  "Turkmen",
    "uk":  "Ukrainian",
    "ur":  "Urdu",
    "uz":  "Uzbek",
    "vi":  "Vietnamese",
    "cy":  "Welsh",
    "yi":  "Yiddish",
    "yo":  "Yoruba",
}

# Qwen3-ASR supported languages (from the official model card)
QWEN_LANGUAGES: dict[str, str] = {
    "zh":  "Chinese",
    "en":  "English",
    "yue": "Cantonese",
    "ar":  "Arabic",
    "de":  "German",
    "fr":  "French",
    "es":  "Spanish",
    "pt":  "Portuguese",
    "id":  "Indonesian",
    "it":  "Italian",
    "ko":  "Korean",
    "ru":  "Russian",
    "th":  "Thai",
    "vi":  "Vietnamese",
    "ja":  "Japanese",
    "tr":  "Turkish",
    "hi":  "Hindi",
    "ms":  "Malay",
    "nl":  "Dutch",
    "sv":  "Swedish",
    "da":  "Danish",
    "fi":  "Finnish",
    "pl":  "Polish",
    "cs":  "Czech",
    "fil": "Filipino",
    "fa":  "Persian",
    "el":  "Greek",
    "hu":  "Hungarian",
    "mk":  "Macedonian",
    "ro":  "Romanian",
}

# Whisper: task="translate" always outputs English.
# So if source_lang != "en" and user wants English → translate task.
# Otherwise → transcribe task (output in source_lang).
WHISPER_TRANSLATE_TARGET = "en"
